#!/bin/sh
if [ -d "$1" ]; then
    [ -z "$2" ] && exec ls -Ap "$1"
    cd "$1" || exit
    shift
    exec xiki "$@"
fi
[ -x "$1" ] && exec "./$1"
[ -f "$1" ] && exec xdg-open "$1"
[ -z "$2" ] && exec sh -c "$1"
shift
exec xiki "$@"
