#!/bin/sh
set -eu
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
XIKI_HOME=${XIKI_HOME:-"$XDG_CONFIG_HOME"}
zig build --release=safe
mkdir -p "$XDG_CONFIG_HOME/xiki/scripts"
cp -rf ./scripts "$XDG_CONFIG_HOME/xiki/scripts"
cp -f ./default "$XDG_CONFIG_HOME/xiki/default"

IFS=':'
for i in $PATH; do
    if [ "$i" = ~/.local/bin ]; then
        cp -f ./zig-out/bin/xiki -t ~/.local/bin
        break
    fi
done
